remove from old SugarShield: Special difficulty rule for testnet
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/733733926#L2379
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/733733935#L3096
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/733733935#L3096
```bash
pow.cpp:26:33: error: comparison of integer expressions of different signedness: ‘const int’ and ‘const unsigned int’ [-Werror=sign-compare]
             pindexLast->nHeight >= params.nPowAllowMinDifficultyBlocksAfterHeight.get())
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```