ARM & OSX: ‘const unsigned int’ and ‘const int’ [-Werror=sign-compare]
test/pow_tests.cpp:38:5:   required from here
/home/travis/build/sugarchain-project/yumekawa/depends/arm-linux-gnueabihf/share/../include/boost/test/tools/old/impl.hpp:107:17: error: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Werror=sign-compare]